version: "3.9"
services:

  db:
    image: "mongo:latest"
    container_name: mongo
    ports:
      - 27017:27017
    restart: always

  app:
    build:
      context: .
    container_name: application
    depends_on:
      - db
    ports:
    - 5000:5000
    restart: always

